### PR TITLE
improve angular example

### PR DESCRIPTION
**Pull request by DanielKucal**

### CODE REVIEW

**Comment by PeterStaev** [comment]
Hey @DanielKucal , thanks for your contribution! This has already been adjusted in the core3 branch: https://github.com/PeterStaev/NativeScript-Drop-Down/blob/core3/README.md#example-usage

**Comment by DanielKucal** [comment]
Hi @PeterStaev, I've checked the other branch and I can see `selectedIndex` also is not updated there. Shouldn't it?

**Comment by PeterStaev** [comment]
Not sure what do you mean. The `selectedIndex` is being updated via `[(ngModel)]`.

**Comment by DanielKucal** [comment]
Oh right, I overlooked that. Thanks for response

**Pull request closed without merging**
